name: Backend Order CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'team1-backend-order'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'team1-backend-order'

jobs:
  call-workflow:
    uses: ./.github/workflows/java-ci-cd.yml
    with:
      service_name: order-service
      working_directory: team1-backend-order
      image_name: order-service
    secrets: inherit
