name: Backend Order CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'team1-backend-order'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'team1-backend-order'

permissions:
  contents: write

concurrency:
  group: k8s-manifests-update
  cancel-in-progress: false

jobs:
  call-workflow:
    uses: ./.github/workflows/java-ci-cd.yml
    with:
      service_name: order-service
      working_directory: team1-backend-order
      image_name: order-service
      use_dockerhub: true
    secrets: inherit
